### PR TITLE
fix(input): add cursor position reset after closing prompt

### LINKED ISSUE #2: Cursor position changes after exiting search window
The cursor jumps behind 1 character after opening and closing the search window, making it impossible or cumbersome to open the same search twice, or, for example opening a different search after the first one.

### PR DESCRIPTION
**Pull request by blkgoose**
In this PR I fixed the cursor position after closing the prompt window.

Closes #2

### CODE REVIEW

**Review by danielefongo — COMMENTED** [review]
I'd suggest to pass the original buffer and original window from the `finder`, using the `microscope_closed` event. 

Another point: we have to check that [microscope-files](https://github.com/danielefongo/microscope-files) does not break with this change.

**Comment by blkgoose** [comment]
@danielefongo I'll check and update the PR, I'm gonna put it in draft for the moment being

**Comment by danielefongo** [comment]
Since `finder:close` now focuses the previous window properly (see
https://github.com/danielefongo/microscope/commit/29e434d48131a8ba7fa51d1b596e605b0a1d9a6f), this PR is ok

**Comment by danielefongo** [comment]
Since `finder:close` now focuses the previous window properly (see
https://github.com/danielefongo/microscope/commit/29e434d48131a8ba7fa51d1b596e605b0a1d9a6f), this PR is ok. 

However, I prefer to put this logic on the finder, so I used your code to make the fix in https://github.com/danielefongo/microscope/commit/9158139203df9d21a7fbaa0d0b6e06af62c10ed7

Thanks :pray:

**Pull request closed without merging**
